[workspace]
resolver = "2"
members = [
  "crates/api",
  "crates/config",
  "crates/tui",
  "crates/data",
  "crates/error",
  "crates/player",
  "crates/gytm",
  "crates/state",
]

[workspace.dependencies]
tokio = { version = "1.52.3", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "cookies",
  "native-tls",
] }
ratatui = "0.30"
ratatui-notifications = "0.1.0"
crossterm = "0.29.0"
dirs = "6.0.0"
thiserror = "2.0.18"
sha1_smol = "1.0"
time = { version = "0.3", default-features = false, features = [
  "formatting",
  "local-offset",
] }
rookie = { version = "0.5.6" }
rusqlite = "0.31.0"
url = "2.5.8"
gjson = "0.8.0"
basic-toml = "0.1"

player = { path = "crates/player" }
tui = { path = "crates/tui" }
api = { path = "crates/api" }
data = { path = "crates/data" }
error = { path = "crates/error" }
gytm = { path = "crates/gytm" }
state = { path = "crates/state" }
config = { path = "crates/config" }

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 4
strip = true
